export type QuizTopic = 'stack' | 'queue';

export interface QuizQuestion {
  id: string;
  topic: QuizTopic;
  question: string;
  options: string[];
  answerIndex: number;
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export const QUESTION_BANK: QuizQuestion[] = [
  // Stack (25)
  {
    id: 'stack-01',
    topic: 'stack',
    question: 'Stack tuan theo nguyen ly nao?',
    options: ['FIFO', 'LIFO', 'Random', 'Priority'],
    answerIndex: 1,
    explanation: 'Stack la LIFO: vao sau ra truoc.',
    difficulty: 'easy',
  },
  {
    id: 'stack-02',
    topic: 'stack',
    question: 'Thao tac them phan tu vao stack la gi?',
    options: ['enqueue', 'insert', 'push', 'append'],
    answerIndex: 2,
    explanation: 'Them phan tu vao dinh stack dung push.',
    difficulty: 'easy',
  },
  {
    id: 'stack-03',
    topic: 'stack',
    question: 'Thao tac lay phan tu tren cung khoi stack la gi?',
    options: ['remove', 'dequeue', 'pop', 'shift'],
    answerIndex: 2,
    explanation: 'Pop lay va xoa phan tu top.',
    difficulty: 'easy',
  },
  {
    id: 'stack-04',
    topic: 'stack',
    question: 'Thao tac xem phan tu top ma khong xoa la gi?',
    options: ['peek', 'pop', 'topOff', 'head'],
    answerIndex: 0,
    explanation: 'Peek (hoac top) chi xem gia tri top.',
    difficulty: 'easy',
  },
  {
    id: 'stack-05',
    topic: 'stack',
    question: 'Do phuc tap trung binh cua push/pop tren stack la?',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
    answerIndex: 0,
    explanation: 'Push/pop tai top thuong O(1).',
    difficulty: 'easy',
  },
  {
    id: 'stack-06',
    topic: 'stack',
    question: 'Ung dung nao thuong dung stack?',
    options: ['BFS', 'Undo/Redo', 'Round Robin', 'Dijkstra priority queue'],
    answerIndex: 1,
    explanation: 'Undo/Redo theo logic vao sau xu ly truoc.',
    difficulty: 'easy',
  },
  {
    id: 'stack-07',
    topic: 'stack',
    question: 'Trong call stack, ham nao tra ve truoc?',
    options: ['Ham duoc goi dau tien', 'Ham duoc goi cuoi cung', 'Ham lon nhat', 'Ham nho nhat'],
    answerIndex: 1,
    explanation: 'Call stack cung la LIFO.',
    difficulty: 'medium',
  },
  {
    id: 'stack-08',
    topic: 'stack',
    question: 'Bieu thuc nao co the kiem tra ngoac can bang bang stack?',
    options: ['a+b*c', '(a+b)*(c-d)', 'a^b^c', 'a/b+c'],
    answerIndex: 1,
    explanation: 'Ngoac mo dong co cap phu hop duoc stack ho tro tot.',
    difficulty: 'medium',
  },
  {
    id: 'stack-09',
    topic: 'stack',
    question: 'Voi stack rong, pop se gay ra tinh huong nao?',
    options: ['Overflow', 'Underflow', 'Collision', 'Deadlock'],
    answerIndex: 1,
    explanation: 'Lay du lieu tu stack rong la underflow.',
    difficulty: 'easy',
  },
  {
    id: 'stack-10',
    topic: 'stack',
    question: 'Neu push lan luot A, B, C thi pop dau tien la?',
    options: ['A', 'B', 'C', 'Khong xac dinh'],
    answerIndex: 2,
    explanation: 'Vao sau C se ra truoc.',
    difficulty: 'easy',
  },
  {
    id: 'stack-11',
    topic: 'stack',
    question: 'Stack co the trien khai bang cau truc nao?',
    options: ['Array', 'Linked List', 'Ca hai', 'Chi Tree'],
    answerIndex: 2,
    explanation: 'Array hoac linked list deu duoc.',
    difficulty: 'easy',
  },
  {
    id: 'stack-12',
    topic: 'stack',
    question: 'Infix -> Postfix thuong su dung cau truc nao?',
    options: ['Queue', 'Stack', 'Heap', 'Trie'],
    answerIndex: 1,
    explanation: 'Thuat toan Shunting-yard dung stack toan tu.',
    difficulty: 'medium',
  },
  {
    id: 'stack-13',
    topic: 'stack',
    question: 'Neu chi duoc dung stack, cach dao nguoc chuoi don gian la?',
    options: ['Sort chuoi', 'Push tung ky tu roi pop', 'Dung binary search', 'Duyet BFS'],
    answerIndex: 1,
    explanation: 'Push vao va pop ra se dao thu tu.',
    difficulty: 'medium',
  },
  {
    id: 'stack-14',
    topic: 'stack',
    question: 'Khi nao stack bang array can cap phat mo rong?',
    options: ['Khi stack day', 'Khi stack rong', 'Moi lan push', 'Moi lan pop'],
    answerIndex: 0,
    explanation: 'Array fixed-size can resize khi het cho.',
    difficulty: 'medium',
  },
  {
    id: 'stack-15',
    topic: 'stack',
    question: 'Danh gia dung sai: "Peek lam thay doi kich thuoc stack".',
    options: ['Dung', 'Sai'],
    answerIndex: 1,
    explanation: 'Peek khong xoa them nen size khong doi.',
    difficulty: 'easy',
  },
  {
    id: 'stack-16',
    topic: 'stack',
    question: 'Voi chuoi ngoac "(()())", ket qua kiem tra can bang la?',
    options: ['Can bang', 'Khong can bang', 'Underflow', 'Overflow'],
    answerIndex: 0,
    explanation: 'So ngoac mo va dong khop thu tu.',
    difficulty: 'medium',
  },
  {
    id: 'stack-17',
    topic: 'stack',
    question: 'Voi stack [top-> 7, 5, 2], sau pop thi top moi la?',
    options: ['7', '5', '2', 'rong'],
    answerIndex: 1,
    explanation: 'Pop bo 7, top con lai la 5.',
    difficulty: 'easy',
  },
  {
    id: 'stack-18',
    topic: 'stack',
    question: 'Do phuc tap space toi da cua stack khi duyet de quy sau nhat la?',
    options: ['O(1)', 'O(depth)', 'O(log n)', 'O(n^2)'],
    answerIndex: 1,
    explanation: 'Call stack tang theo do sau de quy.',
    difficulty: 'hard',
  },
  {
    id: 'stack-19',
    topic: 'stack',
    question: 'Trong DFS iterative, cau truc chinh la?',
    options: ['Queue', 'Stack', 'Heap', 'Set'],
    answerIndex: 1,
    explanation: 'DFS iterative day node vao stack.',
    difficulty: 'medium',
  },
  {
    id: 'stack-20',
    topic: 'stack',
    question: 'Neu push X, push Y, pop, push Z thi top cuoi la?',
    options: ['X', 'Y', 'Z', 'rong'],
    answerIndex: 2,
    explanation: 'Y bi pop, sau do Z nam tren cung.',
    difficulty: 'medium',
  },
  {
    id: 'stack-21',
    topic: 'stack',
    question: 'Tinh chat nao KHONG dung voi stack?',
    options: ['Chi truy cap nhanh top', 'Luu theo LIFO', 'Lay phan tu giua O(1)', 'Push/pop O(1)'],
    answerIndex: 2,
    explanation: 'Lay giua khong phai thao tac stack co ban O(1).',
    difficulty: 'hard',
  },
  {
    id: 'stack-22',
    topic: 'stack',
    question: 'Monotonic stack thuong dung de giai bai toan nao?',
    options: ['Tim next greater element', 'Shortest path weighted', 'Merge sort', 'Prefix sum update'],
    answerIndex: 0,
    explanation: 'Monotonic stack toi uu bai toan phan tu lon hon/nhon hon tiep theo.',
    difficulty: 'hard',
  },
  {
    id: 'stack-23',
    topic: 'stack',
    question: 'Khi convert postfix va evaluate, gap toan tu thi?',
    options: ['Push toan tu', 'Pop 2 toan hang', 'Ignore', 'Swap stack'],
    answerIndex: 1,
    explanation: 'Can lay hai toan hang tren cung de tinh.',
    difficulty: 'medium',
  },
  {
    id: 'stack-24',
    topic: 'stack',
    question: 'Vi sao stack phu hop cho backtracking?',
    options: ['Vi FIFO', 'Vi luu lich su trang thai moi nhat', 'Vi sap xep nhanh', 'Vi khong can bo nho'],
    answerIndex: 1,
    explanation: 'Backtracking quay lui trang thai gan nhat truoc.',
    difficulty: 'medium',
  },
  {
    id: 'stack-25',
    topic: 'stack',
    question: 'Voi stack capacity = 3, dang co 3 phan tu, push nua se?',
    options: ['Underflow', 'Overflow', 'Auto sort', 'Khong gi xay ra'],
    answerIndex: 1,
    explanation: 'Them vao stack day la overflow.',
    difficulty: 'easy',
  },

  // Queue (25)
  {
    id: 'queue-01',
    topic: 'queue',
    question: 'Queue tuan theo nguyen ly nao?',
    options: ['LIFO', 'FIFO', 'Random', 'Deque-only'],
    answerIndex: 1,
    explanation: 'Queue la FIFO: vao truoc ra truoc.',
    difficulty: 'easy',
  },
  {
    id: 'queue-02',
    topic: 'queue',
    question: 'Thao tac them phan tu vao queue la?',
    options: ['push', 'enqueue', 'appendLeft', 'insertTop'],
    answerIndex: 1,
    explanation: 'Queue them vao cuoi bang enqueue.',
    difficulty: 'easy',
  },
  {
    id: 'queue-03',
    topic: 'queue',
    question: 'Thao tac lay phan tu dau queue la?',
    options: ['dequeue', 'pop', 'peekTail', 'removeLast'],
    answerIndex: 0,
    explanation: 'Dequeue lay phan tu o dau hang doi.',
    difficulty: 'easy',
  },
  {
    id: 'queue-04',
    topic: 'queue',
    question: 'Xem phan tu dau ma khong xoa thuong la?',
    options: ['front/peek', 'tailPop', 'top', 'shiftOut'],
    answerIndex: 0,
    explanation: 'Front hoac peek chi xem dau queue.',
    difficulty: 'easy',
  },
  {
    id: 'queue-05',
    topic: 'queue',
    question: 'BFS tren do thi thuong dung cau truc nao?',
    options: ['Stack', 'Queue', 'Heap', 'Hash map'],
    answerIndex: 1,
    explanation: 'BFS duyet theo lop, can queue FIFO.',
    difficulty: 'easy',
  },
  {
    id: 'queue-06',
    topic: 'queue',
    question: 'Neu enqueue A, B, C thi dequeue dau tien la?',
    options: ['A', 'B', 'C', 'Khong xac dinh'],
    answerIndex: 0,
    explanation: 'Vao truoc A se ra truoc.',
    difficulty: 'easy',
  },
  {
    id: 'queue-07',
    topic: 'queue',
    question: 'Queue rong ma dequeue se?',
    options: ['Overflow', 'Underflow', 'Rotate', 'Sort'],
    answerIndex: 1,
    explanation: 'Lay tu queue rong la underflow.',
    difficulty: 'easy',
  },
  {
    id: 'queue-08',
    topic: 'queue',
    question: 'Do phuc tap enqueue/dequeue cua queue tot la?',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n^2)'],
    answerIndex: 0,
    explanation: 'Queue thiet ke dung cho thao tac dau-cuoi O(1).',
    difficulty: 'easy',
  },
  {
    id: 'queue-09',
    topic: 'queue',
    question: 'Mo hinh nao gan voi queue nhat?',
    options: ['Stack plates', 'Xep hang mua ve', 'Backtracking', 'Undo editor'],
    answerIndex: 1,
    explanation: 'Nguoi den truoc duoc phuc vu truoc.',
    difficulty: 'easy',
  },
  {
    id: 'queue-10',
    topic: 'queue',
    question: 'Circular queue giai quyet van de nao?',
    options: ['Sap xep nhanh hon', 'Tan dung bo nho khi head di chuyen', 'Tang priority', 'Loai bo underflow'],
    answerIndex: 1,
    explanation: 'Tai su dung vi tri da giai phong trong array.',
    difficulty: 'medium',
  },
  {
    id: 'queue-11',
    topic: 'queue',
    question: 'Trong queue [front-> 4, 8, 9], sau dequeue thi front moi la?',
    options: ['4', '8', '9', 'rong'],
    answerIndex: 1,
    explanation: 'Bo 4, front con lai la 8.',
    difficulty: 'easy',
  },
  {
    id: 'queue-12',
    topic: 'queue',
    question: 'Priority queue khac queue thuong o diem nao?',
    options: ['Van FIFO hoan toan', 'Lay theo do uu tien', 'Chi luu so', 'Khong dequeue duoc'],
    answerIndex: 1,
    explanation: 'Priority queue khong don thuan FIFO.',
    difficulty: 'medium',
  },
  {
    id: 'queue-13',
    topic: 'queue',
    question: 'He thong job processing nao hop voi queue thuong?',
    options: ['Lich su undo', 'Task vao truoc xu ly truoc', 'DFS', 'Call stack'],
    answerIndex: 1,
    explanation: 'Mo hinh producer-consumer thuong dung queue.',
    difficulty: 'medium',
  },
  {
    id: 'queue-14',
    topic: 'queue',
    question: 'Deque la gi?',
    options: ['Queue chi them cuoi', 'Queue hai dau', 'Stack hai dau', 'Heap dac biet'],
    answerIndex: 1,
    explanation: 'Deque cho phep them/xoa ca dau va cuoi.',
    difficulty: 'medium',
  },
  {
    id: 'queue-15',
    topic: 'queue',
    question: 'Neu head va tail cung tang khong quay vong trong array queue, se gap?',
    options: ['Memory leak logic', 'Nhanh hon', 'Underflow het', 'Khong anh huong'],
    answerIndex: 0,
    explanation: 'Co the con cho trong nhung khong tai su dung duoc.',
    difficulty: 'hard',
  },
  {
    id: 'queue-16',
    topic: 'queue',
    question: 'Round-robin scheduler lien quan nhieu den?',
    options: ['Stack', 'Queue', 'Trie', 'Disjoint set'],
    answerIndex: 1,
    explanation: 'Tien trinh het quantum duoc dua ve cuoi hang doi.',
    difficulty: 'medium',
  },
  {
    id: 'queue-17',
    topic: 'queue',
    question: 'Danh gia dung sai: "Front thay doi khi enqueue".',
    options: ['Dung', 'Sai'],
    answerIndex: 1,
    explanation: 'Enqueue o cuoi, front thuong giu nguyen neu queue khong rong.',
    difficulty: 'medium',
  },
  {
    id: 'queue-18',
    topic: 'queue',
    question: 'Queue trien khai bang linked list can giu tham chieu nao de O(1)?',
    options: ['Chi head', 'Chi tail', 'Ca head va tail', 'Khong can tham chieu'],
    answerIndex: 2,
    explanation: 'Can head de dequeue, tail de enqueue nhanh.',
    difficulty: 'hard',
  },
  {
    id: 'queue-19',
    topic: 'queue',
    question: 'Trong BFS, khi tham mot node thi hang xom duoc?',
    options: ['Push vao stack', 'Enqueue vao queue', 'Bo qua', 'Sort roi pop'],
    answerIndex: 1,
    explanation: 'Hang xom moi duoc dua vao cuoi queue.',
    difficulty: 'medium',
  },
  {
    id: 'queue-20',
    topic: 'queue',
    question: 'Neu queue capacity = 3, dang day, enqueue nua se?',
    options: ['Overflow', 'Underflow', 'Rotate', 'Auto expand chac chan'],
    answerIndex: 0,
    explanation: 'Trong queue gioi han, them nua se overflow.',
    difficulty: 'easy',
  },
  {
    id: 'queue-21',
    topic: 'queue',
    question: 'Tinh chat nao KHONG dung voi queue thuong?',
    options: ['FIFO', 'Dequeue o dau', 'Enqueue o cuoi', 'Lay phan tu bat ky O(1)'],
    answerIndex: 3,
    explanation: 'Queue khong toi uu random access.',
    difficulty: 'hard',
  },
  {
    id: 'queue-22',
    topic: 'queue',
    question: 'Hai stack co the dung de mo phong queue vi?',
    options: ['Stack da la queue', 'Dao nguoc thu tu hai lan', 'Nhanh hon heap', 'Khong can pop'],
    answerIndex: 1,
    explanation: 'Chuyen giua hai stack se phuc hoi thu tu FIFO.',
    difficulty: 'hard',
  },
  {
    id: 'queue-23',
    topic: 'queue',
    question: 'Thong so nao thuong theo doi trong queue implementation?',
    options: ['height', 'front/rear/size', 'color', 'depth only'],
    answerIndex: 1,
    explanation: 'Front, rear, size la thong tin cot loi.',
    difficulty: 'medium',
  },
  {
    id: 'queue-24',
    topic: 'queue',
    question: 'Voi queue [A,B], enqueue C, dequeue, phan tu dau moi la?',
    options: ['A', 'B', 'C', 'rong'],
    answerIndex: 1,
    explanation: 'Sau enqueue thanh [A,B,C], dequeue bo A, con B o front.',
    difficulty: 'medium',
  },
  {
    id: 'queue-25',
    topic: 'queue',
    question: 'Khi nao nen dung queue thay vi stack?',
    options: ['Khi can vao sau ra truoc', 'Khi can xu ly theo thu tu den', 'Khi can backtracking', 'Khi can evaluate postfix'],
    answerIndex: 1,
    explanation: 'Xu ly theo thu tu den la bai toan FIFO.',
    difficulty: 'easy',
  },
];

export const STACK_QUESTIONS = QUESTION_BANK.filter((q) => q.topic === 'stack');
export const QUEUE_QUESTIONS = QUESTION_BANK.filter((q) => q.topic === 'queue');
